// Copyright (C) 2024 Van de Walle Bastien
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0

#pragma once

#include "MassEntityHandle.h"
#include "Hitbox/RecallAttackTypes.h"

#include "RecallHitTypes.generated.h"

/**
 * Define a hit, generated by an attack against vulnerable hitboxes.
 */
USTRUCT()
struct RECALLHITBOX_API FRecallHit
{
	GENERATED_BODY()

	/**
	 * Instigator of the hit.
	 */
	UPROPERTY(VisibleAnywhere)
	FMassEntityHandle Instigator;

	/**
	 * Attack that generated the hit.
	 */
	UPROPERTY(VisibleAnywhere)
	FRecallAttackDefinition Attack;
	
	/**
	 * Location where the hit happened.
	 */
	UPROPERTY(VisibleAnywhere)
	FVector Location = FVector::ZeroVector;

	/**
	 * Direction of the hit.
	 */
	UPROPERTY(VisibleAnywhere)
	FVector Direction = FVector::ForwardVector;
};
